//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int Id { get; set; }
        public int LineNumber { get; set; }
        public int Qty { get; set; }
        public Nullable<int> Price { get; set; }
        public int DiscountAmount { get; set; }
        public int LineTotalAmount { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int OrderId_Id { get; set; }
        public int ProductId_Id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
    }
}
