//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttribute
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int ProductId_Id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
